[body]

[body.spine]
bones = [
    { name = "body.spine.lower", parent = "", orientation = 0, slope = 0, rotation = 0, length = 0.3 },
    { name = "body.spine.intermediate_lower", parent = "body.spine.lower", orientation = 0, slope = 0, rotation = 0, length = 0.3 },
    { name = "body.spine.intermediate_upper", parent = "body.spine.intermediate_lower", orientation = 0, slope = 0, rotation = 0, length = 0.3 },
    { name = "body.spine.chest_upper", parent = "body.spine.intermediate_upper", orientation = 0, slope = 0, rotation = 0, length = 0.3 },
    { name = "body.spine.neck", parent = "body.spine.chest_upper", orientation = 0, slope = 0, rotation = 0, length = 0.1 },
    { name = "body.spine.head", parent = "body.spine.neck", orientation = 0, slope = 0, rotation = 0, length = 0.2 }
]

[body.right_arm]
bones = [
    { name = "body.right_arm.shoulder", parent = "body.torso.chest", orientation = 270, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.right_arm.upper_arm", parent = "body.right_arm.shoulder", orientation = 270, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.right_arm.lower_arm", parent = "body.right_arm.upper_arm", orientation = 270, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.right_arm.wrist", parent = "body.right_arm.lower_arm", orientation = 270, slope = 90, rotation = 0, length = 0.1 }
]

[body.right_arm.fingers.thumb]
bones = [
    { name = "body.right_arm.fingers.thumb.lower", parent = "body.right_arm.wrist", orientation = 270, slope = 90, rotation = 0, length = 0.1 },
    { name = "body.right_arm.fingers.thumb.middle", parent = "body.right_arm.fingers.thumb.lower", orientation = 270, slope = 90, rotation = 0, length = 0.1 },
    { name = "body.right_arm.fingers.thumb.tip", parent = "body.right_arm.fingers.thumb.middle", orientation = 270, slope = 90, rotation = 0, length = 0.1 }
]

[body.right_arm.fingers.index]
bones = [
    { name = "body.right_arm.fingers.index.lower", parent = "body.right_arm.wrist", orientation = 170, slope = 120, rotation = 0, length = 0.1 },
    { name = "body.right_arm.fingers.index.middle", parent = "body.right_arm.fingers.index.lower", orientation = 170, slope = 120, rotation = 0, length = 0.1 },
    { name = "body.right_arm.fingers.index.tip", parent = "body.right_arm.fingers.index.middle", orientation = 170, slope = 120, rotation = 0, length = 0.1 }
]

[body.left_arm]
bones = [
    { name = "body.left_arm.shoulder", parent = "body.spine.chest_upper", orientation = 90, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.left_arm.upper_arm", parent = "body.left_arm.shoulder", orientation = 90, slope = 90, rotation = 0, length = 0.3 }
]

[body.left_leg]
bones = [
    { name = "body.left_leg.pelvis", parent = "", orientation = 90, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.left_leg.upper_leg", parent = "body.left_leg.pelvis", orientation = 90, slope = 180, rotation = 0, length = 0.3 }
]




