[bones]

[bones.lower_back]
orientation = 10
slope = 5
rotation = 5
length = 1
vertices = { a = { ratio = 0.1, distance = 10, slope = 5, rotation = 5 }, b = { ratio = 0.1, distance = 10, slope = 5, rotation = 5 }, c = { ratio = 0.1, distance = 10, slope = 5, rotation = 5 } }
faces = { f = ["a", "b", "c"] }

[bones.mid_back]
connection = "bones.lower_back"
origin = "connection.destination"
orientation = { reference = "connection.orientation", offset = 0 }
slope = { reference = "connection.slope", offset = 90 }
rotation = { reference = "connection.rotation", offset = 0 }
length = 1
vertices = { a = { ratio = 0.1, distance = 10, slope = 5, rotation = 5 }, b = { ratio = 0.1, distance = 10, slope = 5, rotation = 5 }, c = { ratio = 0.1, distance = 10, slope = 5, rotation = 5 } }
faces = { f = ["a", "b", "c"] }