[body]

[body.lower_spine]
len = 0.20
orient = 0
slope = 90
rot = 0

[body.lower_spine.skin_verts]
# Vertices with IDs but no triangle references
ls1 = { frac = 0.0, dist = 0.1, rot = 180 }
ls2 = { frac = 0.0, dist = 0.15, rot = 240 }
ls3 = { frac = 0.4, dist = 0.1, rot = 180 }
ls4 = { frac = 0.4, dist = 0.15, rot = 240 }

# Triangle definitions referencing vertex IDs
[body.lower_spine.triangles]
f1 = { verts = ["ls1", "ls2", "ls3"], col = [0.0, 0.0, 1.0, 0.5] }
f2 = { verts = ["ls2", "ls3", "ls4"], col = [1.0, 1.0, 0.0, 0.5] }

[body.lower_spine.middle_spine]
len = 0.18

# Triangle definitions for middle_spine
[body.lower_spine.middle_spine.triangles]

[body.lower_spine.middle_spine.upper_spine]
len = 0.15

[body.lower_spine.middle_spine.upper_spine.left_upper_arm]
len = 0.3
orient = 100
slope = 20
rot = 0

[body.lower_spine.middle_spine.upper_spine.left_upper_arm.left_lower_arm]
len = 0.3

[body.lower_spine.middle_spine.upper_spine.left_upper_arm.left_lower_arm.left_hand]
len = 0.1

[body.lower_spine.middle_spine.upper_spine.right_upper_arm]
len = 0.3
orient = -100
slope = 20
rot = 0

[body.lower_spine.middle_spine.upper_spine.right_upper_arm.right_lower_arm]
len = 0.3

[body.lower_spine.middle_spine.upper_spine.right_upper_arm.right_lower_arm.right_hand]
len = 0.1

[body.lower_spine.middle_spine.upper_spine.neck]
len = 0.12

[body.lower_spine.middle_spine.upper_spine.neck.head]
len = 0.25


[body.left_pelvis]
len = 0.1
orient = 90
slope = 0
rot = 0

[body.left_pelvis.left_upper_leg]
slope = -50
len = 0.3

[body.left_pelvis.left_upper_leg.left_lower_leg]
len = 0.5

[body.left_pelvis.left_upper_leg.left_lower_leg.left_foot]
len = 0.3
slope = 0
orient = -55

[body.right_pelvis]
len = 0.1
orient = -90
slope = 0
rot = 0

[body.right_pelvis.right_upper_leg]
slope = -50
len = 0.3

[body.right_pelvis.right_upper_leg.right_lower_leg]
len = 0.5

[body.right_pelvis.right_upper_leg.right_lower_leg.right_foot]
len = 0.3
slope = 90
orient = 90
rot = 0

