[bones]
# Root
[bones.spine]
parent = ""  # Root bone starts at origin
orientation = 0
slope = 0
rotation = 0
length = 0.6

# Head
[bones.head]
parent = "bones.spine"  # Head starts at spine's end point
orientation = 0
slope = 49
rotation = 0
length = 0.6