[body]
[body.head]
bones = [
    { name = "body.head.head", parent = "body.head.neck", orientation = 0, slope = 0, rotation = 0, length = 0.2 },
    { name = "body.head.neck", parent = "body.torso.spine.chest", orientation = 0, slope = 0, rotation = 0, length = 0.1 }
]

[body.torso]
bones = [
    { name = "body.torso.spine.chest", parent = "body.torso.spine.intermediate_upper", orientation = 0, slope = 0, rotation = 0, length = 0.3 },
    { name = "body.torso.spine.intermediate_upper", parent = "body.torso.spine.intermediate_lower", orientation = 0, slope = 0, rotation = 0, length = 0.3 },
    { name = "body.torso.spine.intermediate_lower", parent = "body.torso.spine.lower", orientation = 0, slope = 0, rotation = 0, length = 0.3 },
    { name = "body.torso.spine.lower", parent = "", orientation = 0, slope = 0, rotation = 0, length = 0.3 }
]

[body.arms]
[body.arms.right]
bones = [
    { name = "body.arms.right.shoulder", parent = "body.torso.spine.chest", orientation = 270, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.arms.right.upper_arm", parent = "body.arms.right.shoulder", orientation = 270, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.arms.right.lower_arm", parent = "body.arms.right.upper_arm", orientation = 270, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.arms.right.wrist", parent = "body.arms.right.lower_arm", orientation = 270, slope = 90, rotation = 0, length = 0.1 }
]

[body.arms.right.fingers.thumb]
bones = [
    { name = "body.arms.right.fingers.thumb.lower", parent = "body.arms.right.wrist", orientation = 270, slope = 90, rotation = 0, length = 0.1 },
    { name = "body.arms.right.fingers.thumb.middle", parent = "body.arms.right.fingers.thumb.lower", orientation = 270, slope = 90, rotation = 0, length = 0.1 },
    { name = "body.arms.right.fingers.thumb.tip", parent = "body.arms.right.fingers.thumb.middle", orientation = 270, slope = 90, rotation = 0, length = 0.1 }
]

[body.arms.right.fingers.index]
bones = [
    { name = "body.arms.right.fingers.index.lower", parent = "body.arms.right.wrist", orientation = 170, slope = 120, rotation = 0, length = 0.1 },
    { name = "body.arms.right.fingers.index.middle", parent = "body.arms.right.fingers.index.lower", orientation = 170, slope = 120, rotation = 0, length = 0.1 },
    { name = "body.arms.right.fingers.index.tip", parent = "body.arms.right.fingers.index.middle", orientation = 170, slope = 120, rotation = 0, length = 0.1 }
]

[body.arms.left]
bones = [
    { name = "body.arms.left.shoulder", parent = "body.torso.spine.chest", orientation = 90, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.arms.left.upper_arm", parent = "body.arms.left.shoulder", orientation = 90, slope = 90, rotation = 0, length = 0.3 }
]

[body.legs.left]
bones = [
    { name = "body.legs.left.pelvis", parent = "", orientation = 90, slope = 90, rotation = 0, length = 0.3 },
    { name = "body.legs.left.upper_leg", parent = "body.legs.left.pelvis", orientation = 90, slope = 180, rotation = 0, length = 0.3 }
]




