vertices = [
    [0.0, 0.0, 0.0],
    [1.0, 0.0, 0.0],
    [1.0, 1.0, 0.0],
    [0.0, 1.0, 0.0]
]

indices = [
    0, 1, 2,
    0, 2, 3
]

metadata = [
    { text = "A" },
    { text = "B" },
    { text = "C" },
    { text = "D" }
]