# Example showing the new triangle definition structure
# This defines a simple triangular shape using the new format

[body]
len = 2.0

# Define a bone
[body.lower_spine]
len = 1.0
rot = 0

# Define skin vertices on this bone
[body.lower_spine.skin_verts]
# Format: vertex_id = { len = position_along_bone, dist = distance_from_bone, rot = degrees }
ls1 = { len = 0.0, dist = 0.1, rot = 0 }
ls2 = { len = 0.5, dist = 0.2, rot = 120 }
ls3 = { len = 1.0, dist = 0.1, rot = 240 }

# Define triangles using the skin vertices
[body.lower_spine.triangles]
# Format: triangle_id = { verts = [vertex_id1, vertex_id2, vertex_id3], col = [r, g, b, a] }
my_triangle = { verts = ["ls1", "ls2", "ls3"], col = [1.0, 0.0, 0.0, 0.5] }

# Another example with a different bone
[body.upper_spine]
len = 1.0
rot = 0

# Define skin vertices
[body.upper_spine.skin_verts]
us1 = { len = 0.0, dist = 0.1, rot = 0 }
us2 = { len = 0.5, dist = 0.2, rot = 120 }
us3 = { len = 1.0, dist = 0.1, rot = 240 }

# Define triangles
[body.upper_spine.triangles]
blue_triangle = { verts = ["us1", "us2", "us3"], col = [0.0, 0.0, 1.0, 0.5] }

# You can define a triangle that uses vertices from different bones
[body.triangles]
# This triangle connects vertices from lower_spine and upper_spine
connecting_triangle = { verts = ["ls1", "us1", "ls2"], col = [0.0, 1.0, 0.0, 0.7] }
